spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://dpg-d8nt21jtqb8s73dim3e0-a.oregon-postgres.render.com/jobportal_99c9}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres_user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:UASVCm5czR5FRhClnOFRxr9T20qTSETY}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI:mongodb+srv://admin:admin@cluster0.b0ao2kv.mongodb.net/jobportal?appName=Cluster0}

server.port=${PORT:8080}